export const state = () => ({
  currencies: [
    {
      pais: "Afganistán",
      moneda: "Afgani",
      simbolo: "؋",
      codigo_iso: "AFN",
    },
    {
      pais: "Albania",
      moneda: "Lek",
      simbolo: "L",
      codigo_iso: "ALL",
    },
    {
      pais: "Reino Unido",
      moneda: "Libra Esterlina",
      simbolo: "£",
      codigo_iso: "GBP",
    },
    {
      pais: "Argelia",
      moneda: "Dinar",
      simbolo: "د.ج",
      codigo_iso: "DZD",
    },
    {
      pais: "Andorra",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Angola",
      moneda: "Kuanza De Angola",
      simbolo: "Kz",
      codigo_iso: "AOA",
    },
    {
      pais: "Argentina",
      moneda: "Peso Argentino",
      simbolo: "$",
      codigo_iso: "ARS",
    },
    {
      pais: "Armenia",
      moneda: "Dram Armenio",
      simbolo: "",
      codigo_iso: "AMD",
    },
    {
      pais: "Aruba",
      moneda: "Florín Arubano",
      simbolo: "ƒ",
      codigo_iso: "AWG",
    },
    {
      pais: "Australia",
      moneda: "Dólar Australiano",
      simbolo: "$",
      codigo_iso: "AUD",
    },
    {
      pais: "Austria",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Azerbayán",
      moneda: "Manat Azerbayano",
      simbolo: "",
      codigo_iso: "AZN",
    },
    {
      pais: "Bahamas",
      moneda: "Dólar De Las Bahamas",
      simbolo: "$",
      codigo_iso: "BSD",
    },
    {
      pais: "Baréin, Bahrein",
      moneda: "Dinar De Baréin",
      simbolo: ".د.ب",
      codigo_iso: "BHD",
    },
    {
      pais: "Bangladés, Bangladesh",
      moneda: "Taka De Bangladés",
      simbolo: "৳",
      codigo_iso: "BDT",
    },
    {
      pais: "Barbados",
      moneda: "Dólar De Las Barbados",
      simbolo: "$",
      codigo_iso: "BBD",
    },
    {
      pais: "Bielorrusia, Belarús",
      moneda: "Rublo Bielorruso",
      simbolo: "Br",
      codigo_iso: "BYR",
    },
    {
      pais: "Bélgica",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Belice",
      moneda: "Dólar Beliceño",
      simbolo: "$",
      codigo_iso: "BZD",
    },
    {
      pais: "Bután",
      moneda: "Gultrum Butanés",
      simbolo: "Nu.",
      codigo_iso: "BTN",
    },
    {
      pais: "Bolivia",
      moneda: "Boliviano",
      simbolo: "Bs.",
      codigo_iso: "BOB",
    },
    {
      pais: "Bosnia y Herzegovina",
      moneda: "Marco Convertible De Bosnia Y Herzegovina",
      simbolo: "KM",
      codigo_iso: "BAM",
    },
    {
      pais: "Botsuana, Botswana",
      moneda: "Pula De Botsuana",
      simbolo: "P",
      codigo_iso: "BWP",
    },
    {
      pais: "Brasil",
      moneda: "Real Brasileño",
      simbolo: "R$",
      codigo_iso: "BRL",
    },
    {
      pais: "Brunéi",
      moneda: "Dólar De Brunei",
      simbolo: "$",
      codigo_iso: "BND",
    },
    {
      pais: "Bulgaria",
      moneda: "Leva Búlgaro",
      simbolo: "лв",
      codigo_iso: "BGN",
    },
    {
      pais: "Burkina Faso",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XOF",
    },
    {
      pais: "Birmania, Myanmar",
      moneda: "Kiat De Birmania",
      simbolo: "K",
      codigo_iso: "MMK",
    },
    {
      pais: "Burundi",
      moneda: "Franco Burundés",
      simbolo: "Fr",
      codigo_iso: "BIF",
    },
    {
      pais: "Camboya",
      moneda: "Riel Camboyano",
      simbolo: "៛",
      codigo_iso: "KHR",
    },
    {
      pais: "Canadá",
      moneda: "Dólar Canadiense",
      simbolo: "$",
      codigo_iso: "CAD",
    },
    {
      pais: "Cabo Verde",
      moneda: "Escudo De Cabo Verde",
      simbolo: "Esc, $",
      codigo_iso: "CVE",
    },
    {
      pais: "Islas Caimán",
      moneda: "Dólar De Las Islas Caimán",
      simbolo: "$",
      codigo_iso: "KYD",
    },
    {
      pais: "República Centroafricana",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XAF",
    },
    {
      pais: "Chad",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XAF",
    },
    {
      pais: "Chile",
      moneda: "Peso Chileno",
      simbolo: "$",
      codigo_iso: "CLP",
    },
    {
      pais: "China",
      moneda: "Yuan, Renminbi",
      simbolo: "¥, 元",
      codigo_iso: "CNY",
    },
    {
      pais: "Colombia",
      moneda: "Peso Colombiano",
      simbolo: "$",
      codigo_iso: "COP",
    },
    {
      pais: "Comores",
      moneda: "Franco Comorano",
      simbolo: "Fr",
      codigo_iso: "KMF",
    },
    {
      pais: "República Democrática del Congo",
      moneda: "Franco Congoleño",
      simbolo: "Fr",
      codigo_iso: "CDF",
    },
    {
      pais: "República del Congo",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XAF",
    },
    {
      pais: "Costa Rica",
      moneda: "Colón Costarricense",
      simbolo: "₡",
      codigo_iso: "CRC",
    },
    {
      pais: "Costa de Marfil, Côte d'Ivoire",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XOF",
    },
    {
      pais: "Croacia",
      moneda: "Kuna Croata",
      simbolo: "kn",
      codigo_iso: "HRK",
    },
    {
      pais: "Cuba",
      moneda: "Peso Cubano",
      simbolo: "$",
      codigo_iso: "CUP",
    },
    {
      pais: "Curação",
      moneda: "Florín De Las Antillas Neerlandesas",
      simbolo: "ƒ",
      codigo_iso: "ANG",
    },
    {
      pais: "Chipre",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "República Checa",
      moneda: "Corona Checa",
      simbolo: "Kč",
      codigo_iso: "CZK",
    },
    {
      pais: "Dinamarca",
      moneda: "Corona Danesa",
      simbolo: "kr",
      codigo_iso: "DKK",
    },
    {
      pais: "Yibuti, Djibouti",
      moneda: "Franco Yibutiano",
      simbolo: "Fr",
      codigo_iso: "DJF",
    },
    {
      pais: "República Dominicana",
      moneda: "Peso Dominicano",
      simbolo: "$",
      codigo_iso: "DOP",
    },
    {
      pais: "Ecuador",
      moneda: "Dólar Estadounidense",
      simbolo: "$",
      codigo_iso: "USD",
    },
    {
      pais: "Egipto",
      moneda: "Libra Egipcia",
      simbolo: "£, ج.م",
      codigo_iso: "EGP",
    },
    {
      pais: "El Salvador",
      moneda: "Colón Salvadoreño",
      simbolo: "₡",
      codigo_iso: "SVC",
    },
    {
      pais: "Guinea Ecuatorial",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XAF",
    },
    {
      pais: "Eritrea",
      moneda: "Nakfa De Eritrea",
      simbolo: "Nfk",
      codigo_iso: "ERN",
    },
    {
      pais: "Estonia",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Etiopía",
      moneda: "Bir",
      simbolo: "Br",
      codigo_iso: "ETB",
    },
    {
      pais: "Finlandia",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Francia",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Polinesia Francesa",
      moneda: "Franco Cfp",
      simbolo: "Fr",
      codigo_iso: "XPF",
    },
    {
      pais: "Gabón",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XAF",
    },
    {
      pais: "Gambia",
      moneda: "Dalasi Gambiano",
      simbolo: "D",
      codigo_iso: "GMD",
    },
    {
      pais: "Georgia",
      moneda: "Lari Georgiano",
      simbolo: "ლ",
      codigo_iso: "GEL",
    },
    {
      pais: "Alemania",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Ghana [1]",
      moneda: "Cedi De Ghana",
      simbolo: "₵",
      codigo_iso: "GHS",
    },
    {
      pais: "Gibraltar",
      moneda: "Libra De Gibraltar",
      simbolo: "£",
      codigo_iso: "GIP",
    },
    {
      pais: "Grecia",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Guatemala",
      moneda: "Quetzal",
      simbolo: "Q",
      codigo_iso: "GTQ",
    },
    {
      pais: "Guinea",
      moneda: "Franco Guineano",
      simbolo: "Fr",
      codigo_iso: "GNF",
    },
    {
      pais: "Guinea-Bisáu, Guinea Bissau",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XOF",
    },
    {
      pais: "Haití",
      moneda: "Gurde",
      simbolo: "G",
      codigo_iso: "HTG",
    },
    {
      pais: "Honduras",
      moneda: "Lempira",
      simbolo: "L",
      codigo_iso: "HNL",
    },
    {
      pais: "Hungria",
      moneda: "Forinto",
      simbolo: "Ft",
      codigo_iso: "HUF",
    },
    {
      pais: "Islandia",
      moneda: "Corona Islandesa",
      simbolo: "kr",
      codigo_iso: "ISK",
    },
    {
      pais: "India",
      moneda: "Rupia India",
      simbolo: "₹",
      codigo_iso: "INR",
    },
    {
      pais: "Indonesia",
      moneda: "Rupia Indonesia",
      simbolo: "Rp",
      codigo_iso: "IDR",
    },
    {
      pais: "Irán",
      moneda: "Rial Iraní",
      simbolo: "﷼",
      codigo_iso: "IRR",
    },
    {
      pais: "Irak",
      moneda: "Dinar Irakí",
      simbolo: "ع.د",
      codigo_iso: "IQD",
    },
    {
      pais: "Irlanda",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Israel",
      moneda: "Nuevo Séquel",
      simbolo: "₪",
      codigo_iso: "ILS",
    },
    {
      pais: "Italia",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Jamaica",
      moneda: "Dólar Jamaicano",
      simbolo: "$",
      codigo_iso: "JMD",
    },
    {
      pais: "Japón",
      moneda: "Yen",
      simbolo: "¥",
      codigo_iso: "JPY",
    },
    {
      pais: "Jordania",
      moneda: "Dinar Jordano",
      simbolo: "د.ا",
      codigo_iso: "JOD",
    },
    {
      pais: "Kazajistán, Kazajstán",
      moneda: "Tengue Kazajo",
      simbolo: "₸",
      codigo_iso: "KZT",
    },
    {
      pais: "Kenia, Kenya",
      moneda: "Chelín Keniano",
      simbolo: "Sh",
      codigo_iso: "KES",
    },
    {
      pais: "Corea del Norte",
      moneda: "Won Norcoreano",
      simbolo: "₩",
      codigo_iso: "KPW",
    },
    {
      pais: "Corea del Sur",
      moneda: "Won Surcoreano",
      simbolo: "₩",
      codigo_iso: "KRW",
    },
    {
      pais: "Kuwait",
      moneda: "Dinar Kuwaití",
      simbolo: "د.ك",
      codigo_iso: "KWD",
    },
    {
      pais: "Kirguzistán",
      moneda: "Som Kirguís",
      simbolo: "лв",
      codigo_iso: "KGS",
    },
    {
      pais: "Laos",
      moneda: "Kip",
      simbolo: "₭",
      codigo_iso: "LAK",
    },
    {
      pais: "Letonia",
      moneda: "Lats",
      simbolo: "Ls",
      codigo_iso: "LVL",
    },
    {
      pais: "Líbano",
      moneda: "Libra Libanesa",
      simbolo: "ل.ل",
      codigo_iso: "LBP",
    },
    {
      pais: "Lesoto, Lesotho",
      moneda: "Loti De Lesoto",
      simbolo: "L",
      codigo_iso: "LSL",
    },
    {
      pais: "Liberia",
      moneda: "Dólar Liberiano",
      simbolo: "$",
      codigo_iso: "LRD",
    },
    {
      pais: "Libia",
      moneda: "Dinar Libio",
      simbolo: "ل.د",
      codigo_iso: "LYD",
    },
    {
      pais: "Lituania",
      moneda: "Litas",
      simbolo: "Lt",
      codigo_iso: "LTL",
    },
    {
      pais: "Luxemburgo",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Macao",
      moneda: "Pataca De Macao",
      simbolo: "P",
      codigo_iso: "MOP",
    },
    {
      pais: "Macedonia",
      moneda: "Denar",
      simbolo: "ден",
      codigo_iso: "MKD",
    },
    {
      pais: "Madagascar",
      moneda: "Ariari",
      simbolo: "Ar",
      codigo_iso: "MGA",
    },
    {
      pais: "Malaui, Malawi",
      moneda: "Kuacha De Malaui",
      simbolo: "MK",
      codigo_iso: "MWK",
    },
    {
      pais: "Malasia",
      moneda: "Ringit",
      simbolo: "RM",
      codigo_iso: "MYR",
    },
    {
      pais: "Maldivas",
      moneda: "Rufiya",
      simbolo: ".ރ",
      codigo_iso: "MVR",
    },
    {
      pais: "Mali",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XOF",
    },
    {
      pais: "Malta",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Mauritania",
      moneda: "Uguiya",
      simbolo: "UM",
      codigo_iso: "MRO",
    },
    {
      pais: "Mauricio",
      moneda: "Rupia De Mauricio",
      simbolo: "₨",
      codigo_iso: "MUR",
    },
    {
      pais: "México",
      moneda: "Peso Mexicano",
      simbolo: "$",
      codigo_iso: "MXN",
    },
    {
      pais: "Estados Federados de Micronesia",
      moneda: "Dólar Micronesio",
      simbolo: "$",
      codigo_iso: "nenhum",
    },
    {
      pais: "Moldavia",
      moneda: "Leu Moldavo",
      simbolo: "L",
      codigo_iso: "MDL",
    },
    {
      pais: "Mónaco",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Mongolia",
      moneda: "Tugrik Mongol",
      simbolo: "₮",
      codigo_iso: "MNT",
    },
    {
      pais: "Montenegro",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Marruecos",
      moneda: "Dírham",
      simbolo: "د.م.",
      codigo_iso: "MAD",
    },
    {
      pais: "Mozambique",
      moneda: "Metical",
      simbolo: "MT",
      codigo_iso: "MZN",
    },
    {
      pais: "Namibia",
      moneda: "Dólar De Namibia",
      simbolo: "$",
      codigo_iso: "NAD",
    },
    {
      pais: "Nauru",
      moneda: "Dólar Nauruano",
      simbolo: "$",
      codigo_iso: "Nenhum",
    },
    {
      pais: "Nepal",
      moneda: "Rupia Nepalí",
      simbolo: "₨",
      codigo_iso: "NPR",
    },
    {
      pais: "Países Bajos",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Nueva Caledonia",
      moneda: "Franco Cfp",
      simbolo: "Fr",
      codigo_iso: "XPF",
    },
    {
      pais: "Nueva Zelanda",
      moneda: "Dólar De Nueva Zelanda",
      simbolo: "$",
      codigo_iso: "NZD",
    },
    {
      pais: "Nicaragua",
      moneda: "Córdoba Nicaragüense",
      simbolo: "C$",
      codigo_iso: "NIO",
    },
    {
      pais: "Níger",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XOF",
    },
    {
      pais: "Nigeria",
      moneda: "Naira Nigeriano",
      simbolo: "₦",
      codigo_iso: "NGN",
    },
    {
      pais: "Noruega",
      moneda: "Corona Noruega",
      simbolo: "kr",
      codigo_iso: "NOK",
    },
    {
      pais: "Omán",
      moneda: "Rial De Omán",
      simbolo: "ر.ع.",
      codigo_iso: "OMR",
    },
    {
      pais: "Paquistán",
      moneda: "Rupia Pakistaní",
      simbolo: "₨",
      codigo_iso: "PKR",
    },
    {
      pais: "Panamá",
      moneda: "Balboa Panameño",
      simbolo: "B/.",
      codigo_iso: "PAB",
    },
    {
      pais: "Papua-Nueva Guiné",
      moneda: "Kina",
      simbolo: "K",
      codigo_iso: "PGK",
    },
    {
      pais: "Paraguay",
      moneda: "Guaraní Paraguayo",
      simbolo: "₲",
      codigo_iso: "PYG",
    },
    {
      pais: "Perú",
      moneda: "Sol",
      simbolo: "S/",
      codigo_iso: "PEN",
    },
    {
      pais: "Filipinas",
      moneda: "Peso Filipino",
      simbolo: "₱",
      codigo_iso: "PHP",
    },
    {
      pais: "Polonia",
      moneda: "Złóti",
      simbolo: "zł",
      codigo_iso: "PLN",
    },
    {
      pais: "Portugal",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Catar, Qatar",
      moneda: "Rial Catarí",
      simbolo: "ر.ق",
      codigo_iso: "QAR",
    },
    {
      pais: "Rumanía",
      moneda: "Leu Rumano",
      simbolo: "L",
      codigo_iso: "RON",
    },
    {
      pais: "Rusia",
      moneda: "Rublo",
      simbolo: "₽",
      codigo_iso: "RUB",
    },
    {
      pais: "Ruanda, Rwanda",
      moneda: "Franco Ruandés",
      simbolo: "Fr",
      codigo_iso: "RWF",
    },
    {
      pais: "San Cristóbal y Nieves, Saint Kitts y Nevis",
      moneda: "Dólar Del Caribe Oriental",
      simbolo: "$",
      codigo_iso: "XCD",
    },
    {
      pais: "Santa Lucía",
      moneda: "Dólar Del Caribe Oriental",
      simbolo: "$",
      codigo_iso: "XCD",
    },
    {
      pais: "San Viccente y las Granadinas",
      moneda: "Dólar Del Caribe Oriental",
      simbolo: "$",
      codigo_iso: "XCD",
    },
    {
      pais: "Samoa",
      moneda: "Tala",
      simbolo: "T",
      codigo_iso: "WST",
    },
    {
      pais: "San Marino",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Santo Tomé y Príncipe",
      moneda: "Dobra",
      simbolo: "Db",
      codigo_iso: "STD",
    },
    {
      pais: "Arabia Saudí",
      moneda: "Rial Saudí",
      simbolo: "ر.س",
      codigo_iso: "SAR",
    },
    {
      pais: "Senegal",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XOF",
    },
    {
      pais: "Serbia",
      moneda: "Dinar Serbio",
      simbolo: "дин. o din.",
      codigo_iso: "RSD",
    },
    {
      pais: "Seichelles",
      moneda: "Rupia Seychellense",
      simbolo: "₨",
      codigo_iso: "SCR",
    },
    {
      pais: "Sierra Leona",
      moneda: "Leona",
      simbolo: "Le",
      codigo_iso: "SLL",
    },
    {
      pais: "Singapur",
      moneda: "Dólar Singapurense",
      simbolo: "$",
      codigo_iso: "SGD",
    },
    {
      pais: "Eslovaquia",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Eslovenia",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Islas Salomón",
      moneda: "Dólar Salomonense",
      simbolo: "$",
      codigo_iso: "SBD",
    },
    {
      pais: "Somalia",
      moneda: "Chelín Somalí",
      simbolo: "Sh",
      codigo_iso: "SOS",
    },
    {
      pais: "Sudáfrica",
      moneda: "Rand",
      simbolo: "R",
      codigo_iso: "ZAR",
    },
    {
      pais: "España",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Sudán del Sur",
      moneda: "Libra Sursudanesa",
      simbolo: "£",
      codigo_iso: "SSP",
    },
    {
      pais: "Sri Lanka",
      moneda: "Rupia Ceilandesa",
      simbolo: "Rs",
      codigo_iso: "LKR",
    },
    {
      pais: "Sudán",
      moneda: "Libra Sudanesa",
      simbolo: "£",
      codigo_iso: "SDG",
    },
    {
      pais: "Surinám",
      moneda: "Dólar Surinamés",
      simbolo: "$",
      codigo_iso: "SRD",
    },
    {
      pais: "Suazilandia, Swazilandia",
      moneda: "Lilangeni",
      simbolo: "L",
      codigo_iso: "SZL",
    },
    {
      pais: "Suecia",
      moneda: "Corona Sueca",
      simbolo: "kr",
      codigo_iso: "SEK",
    },
    {
      pais: "Suiza",
      moneda: "Franco Suizo",
      simbolo: "Fr",
      codigo_iso: "CHF",
    },
    {
      pais: "Siria",
      moneda: "Libra Siria",
      simbolo: "£ o ل.س",
      codigo_iso: "SYP",
    },
    {
      pais: "Taiwán",
      moneda: "Nuevo Dólar De Taiwán",
      simbolo: "$",
      codigo_iso: "TWD",
    },
    {
      pais: "Tayikistán",
      moneda: "Somoni",
      simbolo: "ЅМ",
      codigo_iso: "TJS",
    },
    {
      pais: "Tanzania",
      moneda: "Chelín Tanzaniano",
      simbolo: "Sh",
      codigo_iso: "TZS",
    },
    {
      pais: "Tailandia",
      moneda: "Bat",
      simbolo: "฿",
      codigo_iso: "THB",
    },
    {
      pais: "Togo",
      moneda: "Franco Cfa",
      simbolo: "Fr",
      codigo_iso: "XOF",
    },
    {
      pais: "Tonga",
      moneda: "Paanga",
      simbolo: "T$",
      codigo_iso: "TOP",
    },
    {
      pais: "Trindade e Tobago",
      moneda: "Dólar Trinitense",
      simbolo: "$",
      codigo_iso: "TTD",
    },
    {
      pais: "Túnez",
      moneda: "Dinar Tunecino",
      simbolo: "د.ت",
      codigo_iso: "TND",
    },
    {
      pais: "Turquia",
      moneda: "Lira Turca",
      simbolo: "",
      codigo_iso: "TRY",
    },
    {
      pais: "Turkmenistán",
      moneda: "Manat Turcomano",
      simbolo: "m",
      codigo_iso: "TMT",
    },
    {
      pais: "Uganda",
      moneda: "Chelín Ugandés",
      simbolo: "Sh",
      codigo_iso: "UGX",
    },
    {
      pais: "Ucrania",
      moneda: "Grivna",
      simbolo: "₴",
      codigo_iso: "UAH",
    },
    {
      pais: "Emiratos Árabes Unidos",
      moneda: "Dírham",
      simbolo: "د.إ",
      codigo_iso: "AED",
    },
    {
      pais: "Estados Unidos",
      moneda: "Dólar Estadounidense",
      simbolo: "$",
      codigo_iso: "USD",
    },
    {
      pais: "Uruguay",
      moneda: "Peso Uruguayo",
      simbolo: "$",
      codigo_iso: "UYU",
    },
    {
      pais: "Uzbequistán",
      moneda: "Sum",
      simbolo: "лв",
      codigo_iso: "UZS",
    },
    {
      pais: "Vanuatu",
      moneda: "Vatu Do Vanuatu",
      simbolo: "Vt",
      codigo_iso: "VUV",
    },
    {
      pais: "Ciudad del Vaticano",
      moneda: "Euro",
      simbolo: "€",
      codigo_iso: "EUR",
    },
    {
      pais: "Venezuela",
      moneda: "Bolívar Fuerte",
      simbolo: "Bs F",
      codigo_iso: "VEF",
    },
    {
      pais: "Vietnam",
      moneda: "Dong",
      simbolo: "₫",
      codigo_iso: "VND",
    },
    {
      pais: "Yemen",
      moneda: "Rial Yemení",
      simbolo: "﷼",
      codigo_iso: "YER",
    },
    {
      pais: "Zambia",
      moneda: "Kuacha Zambiano",
      simbolo: "ZK",
      codigo_iso: "ZMK",
    },
    {
      pais: "Zimbabue, Zimbabwe",
      moneda: "Dólar Zimbabuense",
      simbolo: "$",
      codigo_iso: "ZWL",
    },
  ],
});
export const getters = {
  currencies(state) {
    return state.currencies;
  },
};
